### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by nfour** [fabiandev/ts-runtime#7]
https://fabiandev.github.io/ts-runtime/

```
Uncaught TypeError: Cannot read property 'config' of undefined
    at app.js:1
    at Object.<anonymous> (app.js:1)
    at n (app.js:1)
    at app.js:1
    at app.js:1
```

**Comment by fabiandev** [comment]
Thanks for reporting! The `ts-runtime` version was appended as a query string to the URL for loading [Monaco Editor](https://github.com/Microsoft/monaco-editor) from [unpkg](https://unpkg.com), which is obviously not allowed. The issue should be fixed with commit c38491c0798eadb5ec22ff107defa03d12ece5f3.
